import type { Medal, PersonalBest, BibNumber } from '@/types'

export const sampleMedals: Medal[] = [
  {
    id: 'm1',
    raceName: 'London Marathon 2024',
    eventDate: '2024-04-21',
    location: 'London, UK',
    distance: 'Marathon',
    time: '3:45:22',
    pace: '5:20',
    place: 1250,
    category: 'Senior Men',
    medalColor: 'gold',
    notes: 'Incredible atmosphere! Beat my target by 5 minutes.',
  },
  {
    id: 'm2',
    raceName: 'Brighton 10K',
    eventDate: '2024-03-10',
    location: 'Brighton, UK',
    distance: '10K',
    time: '42:15',
    pace: '4:13',
    place: 89,
    category: 'Senior Men',
    medalColor: 'silver',
    notes: 'Flat and fast course. New PB!',
  },
  {
    id: 'm3',
    raceName: 'Parkrun #50',
    eventDate: '2024-06-01',
    location: 'Bushy Park, London',
    distance: '5K',
    time: '19:48',
    pace: '3:57',
    place: 5,
    category: 'Senior Men',
    medalColor: 'bronze',
    notes: 'Sub-20! Milestone achievement.',
  },
  {
    id: 'm4',
    raceName: 'Berlin Marathon 2023',
    eventDate: '2023-09-24',
    location: 'Berlin, Germany',
    distance: 'Marathon',
    time: '3:52:10',
    pace: '5:30',
    place: 2100,
    category: 'Senior Men',
    medalColor: 'gold',
    notes: 'First marathon! Unforgettable experience.',
  },
  {
    id: 'm5',
    raceName: 'Royal Parks Half',
    eventDate: '2023-10-08',
    location: 'London, UK',
    distance: 'Half Marathon',
    time: '1:42:30',
    pace: '4:51',
    place: 340,
    category: 'Senior Men',
    medalColor: 'silver',
    notes: 'Scenic route through Hyde Park.',
  },
]

export const samplePBs: PersonalBest[] = [
  {
    id: 'pb1',
    distance: '5K',
    time: '19:48',
    pace: '3:57',
    date: '2024-06-01',
    race: 'Parkrun #50',
    isStravaImported: true,
  },
  {
    id: 'pb2',
    distance: '10K',
    time: '42:15',
    pace: '4:13',
    date: '2024-03-10',
    race: 'Brighton 10K',
    isStravaImported: true,
  },
  {
    id: 'pb3',
    distance: 'Half Marathon',
    time: '1:42:30',
    pace: '4:51',
    date: '2023-10-08',
    race: 'Royal Parks Half',
    isStravaImported: false,
  },
  {
    id: 'pb4',
    distance: 'Marathon',
    time: '3:45:22',
    pace: '5:20',
    date: '2024-04-21',
    race: 'London Marathon 2024',
    isStravaImported: true,
  },
  {
    id: 'pb5',
    distance: '1 Mile',
    time: '6:05',
    pace: '3:47',
    date: '2024-05-15',
    race: 'Mile Time Trial',
    isStravaImported: false,
  },
]

export const sampleBibs: BibNumber[] = [
  {
    id: 'b1',
    number: 'A1250',
    raceName: 'London Marathon 2024',
    eventDate: '2024-04-21',
    distance: 'Marathon',
    notes: 'First marathon bib!',
  },
  {
    id: 'b2',
    number: '089',
    raceName: 'Brighton 10K',
    eventDate: '2024-03-10',
    distance: '10K',
    notes: 'Had to pin this one carefully - windy conditions!',
  },
  {
    id: 'b3',
    number: '42195',
    raceName: 'Berlin Marathon 2023',
    eventDate: '2023-09-24',
    distance: 'Marathon',
    notes: 'Berlin marathon - wave 2 start.',
  },
]
